# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_items', to='belt.User'),
        ),
    ]
