# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0004_auto_20170818_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_trip', to='belt.User')),
                ('users_trips', models.ManyToManyField(related_name='tripsadded', to='belt.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='wish',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='users_wish',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
