# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0005_auto_20170829_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.DateTimeField(),
        ),
    ]
