# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0006_auto_20170829_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_by', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='users_trips',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='alias',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='quotes',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_quote', to='belt.User'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='users_quotes',
            field=models.ManyToManyField(related_name='quotesadded', to='belt.User'),
        ),
    ]
