# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0007_auto_20170905_0127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
